/**
 *
 *  NoteTag.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "NoteTag.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::calcite;

const std::string NoteTag::Cols::_note_id = "note_id";
const std::string NoteTag::Cols::_tag_id = "tag_id";
const std::vector<std::string> NoteTag::primaryKeyName = {"note_id","tag_id"};
const bool NoteTag::hasPrimaryKey = true;
const std::string NoteTag::tableName = "note_tag";

const std::vector<typename NoteTag::MetaData> NoteTag::metaData_={
{"note_id","int64_t","bigint(20)",8,0,1,1},
{"tag_id","int64_t","bigint(20)",8,0,1,1}
};
const std::string &NoteTag::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
NoteTag::NoteTag(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["note_id"].isNull())
        {
            noteId_=std::make_shared<int64_t>(r["note_id"].as<int64_t>());
        }
        if(!r["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>(r["tag_id"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            noteId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            tagId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

NoteTag::NoteTag(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            noteId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

NoteTag::NoteTag(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("note_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["note_id"].isNull())
        {
            noteId_=std::make_shared<int64_t>((int64_t)pJson["note_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
}

void NoteTag::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            noteId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void NoteTag::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("note_id"))
    {
        if(!pJson["note_id"].isNull())
        {
            noteId_=std::make_shared<int64_t>((int64_t)pJson["note_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
}

const int64_t &NoteTag::getValueOfNoteId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(noteId_)
        return *noteId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &NoteTag::getNoteId() const noexcept
{
    return noteId_;
}
void NoteTag::setNoteId(const int64_t &pNoteId) noexcept
{
    noteId_ = std::make_shared<int64_t>(pNoteId);
    dirtyFlag_[0] = true;
}

const int64_t &NoteTag::getValueOfTagId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(tagId_)
        return *tagId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &NoteTag::getTagId() const noexcept
{
    return tagId_;
}
void NoteTag::setTagId(const int64_t &pTagId) noexcept
{
    tagId_ = std::make_shared<int64_t>(pTagId);
    dirtyFlag_[1] = true;
}

void NoteTag::updateId(const uint64_t id)
{
}
typename NoteTag::PrimaryKeyType NoteTag::getPrimaryKey() const
{
    return std::make_tuple(*noteId_,*tagId_);
}

const std::vector<std::string> &NoteTag::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "note_id",
        "tag_id"
    };
    return inCols;
}

void NoteTag::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNoteId())
        {
            binder << getValueOfNoteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> NoteTag::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void NoteTag::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getNoteId())
        {
            binder << getValueOfNoteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value NoteTag::toJson() const
{
    Json::Value ret;
    if(getNoteId())
    {
        ret["note_id"]=(Json::Int64)getValueOfNoteId();
    }
    else
    {
        ret["note_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

std::string NoteTag::toString() const
{
    return toJson().toStyledString();
}

Json::Value NoteTag::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getNoteId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfNoteId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTagId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfTagId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getNoteId())
    {
        ret["note_id"]=(Json::Int64)getValueOfNoteId();
    }
    else
    {
        ret["note_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

bool NoteTag::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("note_id"))
    {
        if(!validJsonOfField(0, "note_id", pJson["note_id"], err, true))
            return false;
    }
    else
    {
        err="The note_id column cannot be null";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, true))
            return false;
    }
    else
    {
        err="The tag_id column cannot be null";
        return false;
    }
    return true;
}
bool NoteTag::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NoteTag::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("note_id"))
    {
        if(!validJsonOfField(0, "note_id", pJson["note_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool NoteTag::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool NoteTag::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
