/**
 *
 *  UserTagStat.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace calcite
{

class UserTagStat
{
  public:
    struct Cols
    {
        static const std::string _user_id;
        static const std::string _tag_id;
        static const std::string _view_count;
        static const std::string _like_count;
        static const std::string _collect_count;
        static const std::string _last_action_time;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::vector<std::string> primaryKeyName;
    using PrimaryKeyType = std::tuple<int64_t,int64_t>;//user_id,tag_id
    PrimaryKeyType getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit UserTagStat(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit UserTagStat(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    UserTagStat(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    UserTagStat() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const int64_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const int64_t &pUserId) noexcept;

    /**  For column tag_id  */
    ///Get the value of the column tag_id, returns the default value if the column is null
    const int64_t &getValueOfTagId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getTagId() const noexcept;
    ///Set the value of the column tag_id
    void setTagId(const int64_t &pTagId) noexcept;

    /**  For column view_count  */
    ///Get the value of the column view_count, returns the default value if the column is null
    const int32_t &getValueOfViewCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getViewCount() const noexcept;
    ///Set the value of the column view_count
    void setViewCount(const int32_t &pViewCount) noexcept;
    void setViewCountToNull() noexcept;

    /**  For column like_count  */
    ///Get the value of the column like_count, returns the default value if the column is null
    const int32_t &getValueOfLikeCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLikeCount() const noexcept;
    ///Set the value of the column like_count
    void setLikeCount(const int32_t &pLikeCount) noexcept;
    void setLikeCountToNull() noexcept;

    /**  For column collect_count  */
    ///Get the value of the column collect_count, returns the default value if the column is null
    const int32_t &getValueOfCollectCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getCollectCount() const noexcept;
    ///Set the value of the column collect_count
    void setCollectCount(const int32_t &pCollectCount) noexcept;
    void setCollectCountToNull() noexcept;

    /**  For column last_action_time  */
    ///Get the value of the column last_action_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastActionTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastActionTime() const noexcept;
    ///Set the value of the column last_action_time
    void setLastActionTime(const ::trantor::Date &pLastActionTime) noexcept;
    void setLastActionTimeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<UserTagStat>;
    friend drogon::orm::BaseBuilder<UserTagStat, true, true>;
    friend drogon::orm::BaseBuilder<UserTagStat, true, false>;
    friend drogon::orm::BaseBuilder<UserTagStat, false, true>;
    friend drogon::orm::BaseBuilder<UserTagStat, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<UserTagStat>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> userId_;
    std::shared_ptr<int64_t> tagId_;
    std::shared_ptr<int32_t> viewCount_;
    std::shared_ptr<int32_t> likeCount_;
    std::shared_ptr<int32_t> collectCount_;
    std::shared_ptr<::trantor::Date> lastActionTime_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where user_id = ? and tag_id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where user_id = ? and tag_id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "tag_id,";
            ++parametersCount;
        }
        sql += "view_count,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        sql += "like_count,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        sql += "collect_count,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "last_action_time,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace calcite
} // namespace drogon_model
