/**
 *
 *  UserTagStat.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "UserTagStat.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::calcite;

const std::string UserTagStat::Cols::_user_id = "user_id";
const std::string UserTagStat::Cols::_tag_id = "tag_id";
const std::string UserTagStat::Cols::_view_count = "view_count";
const std::string UserTagStat::Cols::_like_count = "like_count";
const std::string UserTagStat::Cols::_collect_count = "collect_count";
const std::string UserTagStat::Cols::_last_action_time = "last_action_time";
const std::vector<std::string> UserTagStat::primaryKeyName = {"user_id","tag_id"};
const bool UserTagStat::hasPrimaryKey = true;
const std::string UserTagStat::tableName = "user_tag_stat";

const std::vector<typename UserTagStat::MetaData> UserTagStat::metaData_={
{"user_id","int64_t","bigint(20)",8,0,1,1},
{"tag_id","int64_t","bigint(20)",8,0,1,1},
{"view_count","int32_t","int(11)",4,0,0,0},
{"like_count","int32_t","int(11)",4,0,0,0},
{"collect_count","int32_t","int(11)",4,0,0,0},
{"last_action_time","::trantor::Date","datetime",0,0,0,0}
};
const std::string &UserTagStat::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
UserTagStat::UserTagStat(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>(r["tag_id"].as<int64_t>());
        }
        if(!r["view_count"].isNull())
        {
            viewCount_=std::make_shared<int32_t>(r["view_count"].as<int32_t>());
        }
        if(!r["like_count"].isNull())
        {
            likeCount_=std::make_shared<int32_t>(r["like_count"].as<int32_t>());
        }
        if(!r["collect_count"].isNull())
        {
            collectCount_=std::make_shared<int32_t>(r["collect_count"].as<int32_t>());
        }
        if(!r["last_action_time"].isNull())
        {
            auto timeStr = r["last_action_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            tagId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            viewCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            likeCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            collectCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

UserTagStat::UserTagStat(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            viewCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            likeCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            collectCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

UserTagStat::UserTagStat(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
    if(pJson.isMember("view_count"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["view_count"].isNull())
        {
            viewCount_=std::make_shared<int32_t>((int32_t)pJson["view_count"].asInt64());
        }
    }
    if(pJson.isMember("like_count"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["like_count"].isNull())
        {
            likeCount_=std::make_shared<int32_t>((int32_t)pJson["like_count"].asInt64());
        }
    }
    if(pJson.isMember("collect_count"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["collect_count"].isNull())
        {
            collectCount_=std::make_shared<int32_t>((int32_t)pJson["collect_count"].asInt64());
        }
    }
    if(pJson.isMember("last_action_time"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["last_action_time"].isNull())
        {
            auto timeStr = pJson["last_action_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserTagStat::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            viewCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            likeCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            collectCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void UserTagStat::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("user_id"))
    {
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int64_t>((int64_t)pJson["tag_id"].asInt64());
        }
    }
    if(pJson.isMember("view_count"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["view_count"].isNull())
        {
            viewCount_=std::make_shared<int32_t>((int32_t)pJson["view_count"].asInt64());
        }
    }
    if(pJson.isMember("like_count"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["like_count"].isNull())
        {
            likeCount_=std::make_shared<int32_t>((int32_t)pJson["like_count"].asInt64());
        }
    }
    if(pJson.isMember("collect_count"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["collect_count"].isNull())
        {
            collectCount_=std::make_shared<int32_t>((int32_t)pJson["collect_count"].asInt64());
        }
    }
    if(pJson.isMember("last_action_time"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["last_action_time"].isNull())
        {
            auto timeStr = pJson["last_action_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                lastActionTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &UserTagStat::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UserTagStat::getUserId() const noexcept
{
    return userId_;
}
void UserTagStat::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[0] = true;
}

const int64_t &UserTagStat::getValueOfTagId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(tagId_)
        return *tagId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &UserTagStat::getTagId() const noexcept
{
    return tagId_;
}
void UserTagStat::setTagId(const int64_t &pTagId) noexcept
{
    tagId_ = std::make_shared<int64_t>(pTagId);
    dirtyFlag_[1] = true;
}

const int32_t &UserTagStat::getValueOfViewCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(viewCount_)
        return *viewCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserTagStat::getViewCount() const noexcept
{
    return viewCount_;
}
void UserTagStat::setViewCount(const int32_t &pViewCount) noexcept
{
    viewCount_ = std::make_shared<int32_t>(pViewCount);
    dirtyFlag_[2] = true;
}
void UserTagStat::setViewCountToNull() noexcept
{
    viewCount_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &UserTagStat::getValueOfLikeCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(likeCount_)
        return *likeCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserTagStat::getLikeCount() const noexcept
{
    return likeCount_;
}
void UserTagStat::setLikeCount(const int32_t &pLikeCount) noexcept
{
    likeCount_ = std::make_shared<int32_t>(pLikeCount);
    dirtyFlag_[3] = true;
}
void UserTagStat::setLikeCountToNull() noexcept
{
    likeCount_.reset();
    dirtyFlag_[3] = true;
}

const int32_t &UserTagStat::getValueOfCollectCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(collectCount_)
        return *collectCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &UserTagStat::getCollectCount() const noexcept
{
    return collectCount_;
}
void UserTagStat::setCollectCount(const int32_t &pCollectCount) noexcept
{
    collectCount_ = std::make_shared<int32_t>(pCollectCount);
    dirtyFlag_[4] = true;
}
void UserTagStat::setCollectCountToNull() noexcept
{
    collectCount_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &UserTagStat::getValueOfLastActionTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(lastActionTime_)
        return *lastActionTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &UserTagStat::getLastActionTime() const noexcept
{
    return lastActionTime_;
}
void UserTagStat::setLastActionTime(const ::trantor::Date &pLastActionTime) noexcept
{
    lastActionTime_ = std::make_shared<::trantor::Date>(pLastActionTime);
    dirtyFlag_[5] = true;
}
void UserTagStat::setLastActionTimeToNull() noexcept
{
    lastActionTime_.reset();
    dirtyFlag_[5] = true;
}

void UserTagStat::updateId(const uint64_t id)
{
}
typename UserTagStat::PrimaryKeyType UserTagStat::getPrimaryKey() const
{
    return std::make_tuple(*userId_,*tagId_);
}

const std::vector<std::string> &UserTagStat::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "user_id",
        "tag_id",
        "view_count",
        "like_count",
        "collect_count",
        "last_action_time"
    };
    return inCols;
}

void UserTagStat::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getViewCount())
        {
            binder << getValueOfViewCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLikeCount())
        {
            binder << getValueOfLikeCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCollectCount())
        {
            binder << getValueOfCollectCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLastActionTime())
        {
            binder << getValueOfLastActionTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> UserTagStat::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void UserTagStat::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getViewCount())
        {
            binder << getValueOfViewCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLikeCount())
        {
            binder << getValueOfLikeCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCollectCount())
        {
            binder << getValueOfCollectCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLastActionTime())
        {
            binder << getValueOfLastActionTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value UserTagStat::toJson() const
{
    Json::Value ret;
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    if(getViewCount())
    {
        ret["view_count"]=getValueOfViewCount();
    }
    else
    {
        ret["view_count"]=Json::Value();
    }
    if(getLikeCount())
    {
        ret["like_count"]=getValueOfLikeCount();
    }
    else
    {
        ret["like_count"]=Json::Value();
    }
    if(getCollectCount())
    {
        ret["collect_count"]=getValueOfCollectCount();
    }
    else
    {
        ret["collect_count"]=Json::Value();
    }
    if(getLastActionTime())
    {
        ret["last_action_time"]=getLastActionTime()->toDbStringLocal();
    }
    else
    {
        ret["last_action_time"]=Json::Value();
    }
    return ret;
}

std::string UserTagStat::toString() const
{
    return toJson().toStyledString();
}

Json::Value UserTagStat::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTagId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfTagId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getViewCount())
            {
                ret[pMasqueradingVector[2]]=getValueOfViewCount();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLikeCount())
            {
                ret[pMasqueradingVector[3]]=getValueOfLikeCount();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCollectCount())
            {
                ret[pMasqueradingVector[4]]=getValueOfCollectCount();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLastActionTime())
            {
                ret[pMasqueradingVector[5]]=getLastActionTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=(Json::Int64)getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    if(getViewCount())
    {
        ret["view_count"]=getValueOfViewCount();
    }
    else
    {
        ret["view_count"]=Json::Value();
    }
    if(getLikeCount())
    {
        ret["like_count"]=getValueOfLikeCount();
    }
    else
    {
        ret["like_count"]=Json::Value();
    }
    if(getCollectCount())
    {
        ret["collect_count"]=getValueOfCollectCount();
    }
    else
    {
        ret["collect_count"]=Json::Value();
    }
    if(getLastActionTime())
    {
        ret["last_action_time"]=getLastActionTime()->toDbStringLocal();
    }
    else
    {
        ret["last_action_time"]=Json::Value();
    }
    return ret;
}

bool UserTagStat::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, true))
            return false;
    }
    else
    {
        err="The tag_id column cannot be null";
        return false;
    }
    if(pJson.isMember("view_count"))
    {
        if(!validJsonOfField(2, "view_count", pJson["view_count"], err, true))
            return false;
    }
    if(pJson.isMember("like_count"))
    {
        if(!validJsonOfField(3, "like_count", pJson["like_count"], err, true))
            return false;
    }
    if(pJson.isMember("collect_count"))
    {
        if(!validJsonOfField(4, "collect_count", pJson["collect_count"], err, true))
            return false;
    }
    if(pJson.isMember("last_action_time"))
    {
        if(!validJsonOfField(5, "last_action_time", pJson["last_action_time"], err, true))
            return false;
    }
    return true;
}
bool UserTagStat::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserTagStat::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(0, "user_id", pJson["user_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("view_count"))
    {
        if(!validJsonOfField(2, "view_count", pJson["view_count"], err, false))
            return false;
    }
    if(pJson.isMember("like_count"))
    {
        if(!validJsonOfField(3, "like_count", pJson["like_count"], err, false))
            return false;
    }
    if(pJson.isMember("collect_count"))
    {
        if(!validJsonOfField(4, "collect_count", pJson["collect_count"], err, false))
            return false;
    }
    if(pJson.isMember("last_action_time"))
    {
        if(!validJsonOfField(5, "last_action_time", pJson["last_action_time"], err, false))
            return false;
    }
    return true;
}
bool UserTagStat::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool UserTagStat::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
